#!/usr/bin/env python3
"""One-off migration of this LLM Wiki to an Ar9av/obsidian-wiki vault.

Ran once on 2026-10-04 against commit ce821ab (the old top-level wiki/,
raw/, index.md… were removed afterwards). Kept for the record.

Usage:
    python3 .claude/scripts/migrate-to-obsidian-wiki.py <vault-dir>          # dry run
    python3 .claude/scripts/migrate-to-obsidian-wiki.py <vault-dir> --apply  # write

Stdlib only (plus the `obsidian-wiki` CLI on --apply). Reads wiki/, raw/, index.md, _index-*.md, log.md, .obsidian/ from
the repo root; never modifies them. Writes into <vault-dir>, which must be empty
or absent on --apply. Prints a report either way.

Mapping:
  type: entity       -> entities/<slug>.md   (wiki/people/* included)
  type: concept      -> concepts/<slug>.md
  type: source       -> references/<slug>.md
  type: comparison   -> synthesis/<slug>.md
  type: overview     -> synthesis/<slug>.md
  type: link         -> references/<slug>.md
  date               -> created (ISO); updated = max(date, last git commit on file)
  source_url         -> sources: ["url:<url>"]; raw capture -> sources: ["_raw/_archived/<f>"]
  captured, version  -> kept (owner extensions, documented in vault AGENTS.md)
  index one-liners   -> summary
  [[slug]], [[people/slug]] -> [[<category>/<slug>]] (alias/heading preserved);
  links to pages that never existed become plain text (listed in the report)
  raw/*              -> _raw/_archived/*
  _index-*.md, _hot.md, index.md -> dropped (regenerated by `obsidian-wiki memory`)
  log.md             -> _archives/llm-wiki-log.md (verbatim history)
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WIKI = ROOT / "wiki"
RAW = ROOT / "raw"
ARCHIVE = "_raw/_archived"

CATEGORY = {
    "entity": "entities",
    "concept": "concepts",
    "source": "references",
    "comparison": "synthesis",
    "overview": "synthesis",
    "link": "references",
}

# Known typos in the old wiki's links: wrong target -> right target.
LINK_FIXES = {
    "justice-pedo-criminalite-france": "justice-pedocriminalite-france",
}

VAULT_AGENTS = """# Owner conventions

Personal knowledge base: reading (books, articles), listening (podcasts,
videos), and notes on personal viewpoints. Migrated on 2026-10-04 from a
hand-rolled LLM Wiki; its log is kept in `_archives/llm-wiki-log.md`.

## Language

Bilingual, French and English. **Do not translate.** Write a page in the
language of its source or of the owner's note, and keep that language when
updating it later.

## Content boundary

No employer content: no internal documents, nothing derived from them, no
internal names. This vault is pushed to GitHub and read by hosted services.

## Frontmatter extensions

On top of the framework fields (`title, category, tags, sources, summary,
created, updated`):

- `captured` — date the raw snapshot was taken, or `pending` / `failed — <reason>`
  when capture did not succeed. Never summarize content that was not captured.
- `version` — source version when it has one (edition/ISBN, document revision,
  git SHA). Used to detect staleness.

Trust fields (`base_confidence`, `lifecycle`) are not set on migrated pages;
treat their absence as unreviewed, not as an error to fill in automatically.

## Categories

- `references/` — one page per ingested source (article, video, podcast, book).
- `entities/` — people, organisations, named affairs.
- `concepts/` — ideas and recurring themes.
- `synthesis/` — comparisons and cross-source analysis.

## Ingest

Capture first: keep an immutable snapshot under `_raw/_archived/` before
summarizing. Podcasts: Apple Podcasts or RSS link (not Spotify). Videos:
transcript via `yt-dlp` when available.
"""

LINK_RE = re.compile(r"\[\[([^\]\|#\n]+)(#[^\]\|\n]*)?(\|[^\]\n]*)?\]\]")
INDEX_LINE_RE = re.compile(r"^- \[\[([^\]\|#]+)(?:\|[^\]]*)?\]\]\s+—\s+(.+)$")
RAW_REF_RE = re.compile(r"`raw/([^`]+)`")


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return {}, text
    end = text.index("\n---", 4)
    fm, body = text[4:end], text[end + 4 :].lstrip("\n")
    data = {}
    for line in fm.splitlines():
        m = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip().strip("\"'") for v in val[1:-1].split(",") if v.strip()]
        data[key] = val
    return data, body


def git_last_date(path):
    out = subprocess.run(
        ["git", "-C", str(ROOT), "log", "-1", "--format=%cs", "--", str(path)],
        capture_output=True, text=True,
    ).stdout.strip()
    return out or None


def load_summaries():
    summaries = {}
    for f in sorted(ROOT.glob("_index-*.md")) + [ROOT / "index.md"]:
        if not f.exists():
            continue
        for line in f.read_text().splitlines():
            m = INDEX_LINE_RE.match(line.strip())
            if m:
                slug = m.group(1).split("/")[-1]
                summaries.setdefault(slug, m.group(2).strip())
    return summaries


def first_paragraph(body):
    for para in body.split("\n\n"):
        p = para.strip()
        if p and not p.startswith(("#", ">", "-", "|", "*")):
            p = re.sub(r"\[\[([^\]\|]+\|)?([^\]]+)\]\]", r"\2", p)
            p = re.sub(r"[*_`]", "", " ".join(p.split()))
            return p if len(p) <= 200 else p[:197].rsplit(" ", 1)[0] + "…"
    return ""


def raw_for_url(url):
    for f in RAW.glob("*.md"):
        head = f.read_text(errors="replace")[:2000]
        if url in head:
            return f.name
    return None


def folded(key, value):
    return f"{key}: >-\n  {value}"


def build(vault, apply, cli):
    report = defaultdict(list)
    summaries = load_summaries()

    pages = {}
    for f in sorted(WIKI.rglob("*.md")):
        fm, body = parse_frontmatter(f.read_text())
        slug = f.stem
        if slug in pages:
            sys.exit(f"slug collision: {slug} ({pages[slug]['src']} vs {f})")
        cat = CATEGORY.get(fm.get("type", ""))
        if cat is None:
            report["unknown_type"].append(f"{f.relative_to(ROOT)}: {fm.get('type')!r}")
            cat = "concepts"
        pages[slug] = {"src": f, "fm": fm, "body": body, "cat": cat}

    def resolve(target):
        key = LINK_FIXES.get(target.strip(), target.strip())
        key = key.split("/")[-1].removesuffix(".md")
        return pages.get(key) and f"{pages[key]['cat']}/{key}"

    out = {}
    for slug, p in pages.items():
        fm, body = p["fm"], p["body"]
        rel = f"{p['cat']}/{slug}.md"

        def relink(m):
            target, esc = m.group(1), ""
            if target.endswith("\\"):  # `[[a\|b]]` inside a Markdown table
                target, esc = target[:-1], "\\"
            new = resolve(target)
            if new is None:  # old wiki had no such page: keep the text, drop the link
                report["dangling_links"].append(f"{rel}: [[{target}]]")
                return (m.group(3) or "|" + target.split("/")[-1])[1:]
            if target != new:
                report["links_rewritten"].append(rel)
            return f"[[{new}{m.group(2) or ''}{esc}{m.group(3) or ''}]]"

        body = LINK_RE.sub(relink, body)

        raws = RAW_REF_RE.findall(body)
        url = fm.get("source_url")
        if url and not raws:
            hit = raw_for_url(url)
            if hit:
                raws.append(hit)
        for r in raws:
            if not (RAW / r).exists():
                report["missing_raw"].append(f"{rel}: raw/{r}")
        body = RAW_REF_RE.sub(lambda m: f"`{ARCHIVE}/{m.group(1)}`", body)

        sources = [f"url:{url}"] if url else []
        if not url:
            sources += [f"{ARCHIVE}/{r}" for r in raws]
        if raws or url:
            lines = ["", "## Sources", ""]
            # Wikilinks only for .md snapshots: lint resolves [[x.vtt]] as x.vtt.md.
            lines += [f"- [[{ARCHIVE}/{r[:-3]}]]" if r.endswith(".md")
                      else f"- [{r}](../{ARCHIVE}/{r})" for r in raws]
            if url:
                lines.append(f"- <{url}>")
            body = body.rstrip("\n") + "\n" + "\n".join(lines) + "\n"

        created = fm.get("date") or git_last_date(p["src"]) or "1970-01-01"
        updated = max(created, git_last_date(p["src"]) or created)
        summary = summaries.get(slug) or first_paragraph(body)
        summary = re.sub(r"\[\[([^\]\|]+\|)?([^\]]+)\]\]", r"\2", summary)
        if slug not in summaries:
            report["summary_from_body"].append(rel)

        title = fm.get("title", slug)
        tags = fm.get("tags") or []
        if len(tags) > 5:
            report["over_5_tags"].append(f"{rel}: {len(tags)}")
        fm_lines = [
            folded("title", title),
            f"category: {p['cat']}",
            f"tags: [{', '.join(tags)}]",
            "sources: []" if not sources else "sources:\n" + "\n".join(f'  - "{s}"' for s in sources),
            folded("summary", summary),
            f"created: {created}T00:00:00Z",
            f"updated: {updated}T00:00:00Z",
        ]
        for k in ("captured", "version"):
            if fm.get(k):
                fm_lines.append(f'{k}: "{fm[k]}"')
        dropped = set(fm) - {"title", "type", "date", "sources", "tags", "source_url", "captured", "version"}
        if dropped:
            report["dropped_fields"].append(f"{rel}: {sorted(dropped)}")
        out[rel] = {"text": "---\n" + "\n".join(fm_lines) + "\n---\n\n" + body,
                    "raws": raws, "src": str(p["src"].relative_to(ROOT))}

    raw_files = [f for f in sorted(RAW.rglob("*")) if f.is_file() and f.name != ".gitkeep"]
    referenced = {r for o in out.values() for r in o["raws"]}
    for f in raw_files:
        if f.relative_to(RAW).as_posix() not in referenced:
            report["unreferenced_raw"].append(f.relative_to(RAW).as_posix())

    # --- report ---
    cats = Counter(path.split("/")[0] for path in out)
    print(f"pages: {len(pages)} -> {len(out)}  {dict(sorted(cats.items()))}")
    print(f"raw captures: {len(raw_files)} -> {ARCHIVE}/")
    print(f"links rewritten in {len(set(report['links_rewritten']))} pages")
    for k in ("unknown_type", "missing_raw", "unreferenced_raw", "dangling_links",
              "summary_from_body", "over_5_tags", "dropped_fields"):
        if report[k]:
            print(f"\n{k} ({len(report[k])}):")
            for item in sorted(set(report[k])):
                print(f"  {item}")

    if not apply:
        print("\n(dry run — nothing written; pass --apply)")
        return

    vault = Path(vault).expanduser().resolve()
    if vault.exists() and any(vault.iterdir()):
        sys.exit(f"refusing to write: {vault} is not empty")
    vault.mkdir(parents=True, exist_ok=True)
    for rel, o in out.items():
        dst = vault / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(o["text"])
    for f in raw_files:
        dst = vault / ARCHIVE / f.relative_to(RAW)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(f, dst)
    # Old log is history, not a live page: archive it (lint skips _archives/);
    # `obsidian-wiki memory sync` starts a fresh log.md.
    if (ROOT / "log.md").exists():
        (vault / "_archives").mkdir(exist_ok=True)
        shutil.copy2(ROOT / "log.md", vault / "_archives" / "llm-wiki-log.md")
    obs = ROOT / ".obsidian"
    if obs.is_dir():
        shutil.copytree(obs, vault / ".obsidian",
                        ignore=shutil.ignore_patterns("workspace*.json"))
    (vault / "AGENTS.md").write_text(VAULT_AGENTS)
    (vault / ".okignore").write_text(
        "# Not wiki pages: owner conventions and framework metadata.\n/AGENTS.md\n/_meta\n")
    tag_counts = Counter(t for p in pages.values() for t in (p["fm"].get("tags") or []))
    (vault / "_meta").mkdir(exist_ok=True)
    (vault / "_meta" / "taxonomy.md").write_text(
        "---\ntitle: >-\n  Tag Taxonomy\n---\n\n# Tag Taxonomy\n\n"
        "Tags in use at migration from the LLM Wiki (count = pages).\n\n| Tag | Pages |\n|---|---|\n"
        + "".join(f"| `{t}` | {n} |\n" for t, n in sorted(tag_counts.items(), key=lambda x: (-x[1], x[0]))))
    print(f"\nwrote {len(out)} pages + {len(raw_files)} raw files to {vault}")

    # Framework bookkeeping, through its CLI: snapshots, manifest, memory files.
    def run(*args):
        r = subprocess.run([cli, *args], capture_output=True, text=True)
        if r.returncode:
            sys.exit(f"{' '.join(args)} failed:\n{r.stderr or r.stdout}")
    for rel, o in out.items():
        for r in o["raws"]:
            snap = f"{ARCHIVE}/{r}"
            # lint only resolves wikilinks to .md and media; a .vtt snapshot
            # would show as broken, so it lives in the body Sources section only.
            if r.endswith(".md"):
                run("snapshots", "set", rel, "--archive", snap, "--vault", str(vault))
            run("cache-update", str(vault), snap, "--pages", rel)
    run("memory", "sync", "MIGRATE", "source=llm-wiki-personal", f"pages={len(out)}",
        "--vault", str(vault))
    print("snapshots, .manifest.json, index.md, log.md, hot.md written via obsidian-wiki")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("vault")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--cli", default=shutil.which("obsidian-wiki"),
                    help="obsidian-wiki executable (default: from PATH)")
    a = ap.parse_args()
    if a.apply and not a.cli:
        sys.exit("obsidian-wiki not found; pip install obsidian-wiki or pass --cli")
    build(a.vault, a.apply, a.cli)
